# Generated by Django 4.0 on 2022-01-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_projects_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='isAdmin',
            new_name='isProjectManager',
        ),
    ]
